---
- hosts: us
  gather_facts: True
  tasks:
   - name: Copy file with owner and permissions
     copy:
     src: /root/ansible.txt
     dest: /tmp/
     owner: ec2-user
     group: ec2-user
     mode: '0644'