---
- hosts: remote
  remote_user: root
  tasks:
   - name: Test connection
     ping:
   - name: Install WebServer 
     yum:
        name: httpd
        state: installed
   - name: Starting the service 
     service:
        name: httpd
        state: enabled 
    - name: Copy index.html 
      copy:
        src: index.html
        dst: /var/www/html/